# Generated by Django 2.0.5 on 2018-05-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180525_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_ineligible',
            field=models.DateField(null=True),
        ),
    ]
