# Generated by Django 2.0.5 on 2018-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180525_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='correct_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
