# Generated by Django 2.0.5 on 2018-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180525_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma',
            field=models.SmallIntegerField(default=100),
        ),
    ]
