# Generated by Django 2.0.5 on 2018-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_userprofile_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='eligibility',
            field=models.CharField(choices=[('Yes', 'Y'), ('No', 'N')], default='Yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_ineligible',
            field=models.DateTimeField(null=True),
        ),
    ]
